create table public.genres (
    id bigint generated by default as identity not null,
    title text not null unique,

    primary key(id)
);

create table public.profiles_genres (
    profile uuid not null references profiles on delete cascade,
    genre bigint not null references genres on delete cascade,

    primary key(profile, genre)
);
