create table public.posts (
    id bigint generated by default as identity not null,

    creator uuid not null references auth.users on delete cascade,

    created_at timestamp with time zone not null default now(),

    thumbnail text,
    title text,
    content text
);
