create table "public"."genres" (
    "id" bigint generated by default as identity not null,
    "title" text not null
);


create table "public"."profiles_genres" (
    "profile" uuid not null,
    "genre" bigint not null
);


CREATE UNIQUE INDEX genres_pkey ON public.genres USING btree (id);

CREATE UNIQUE INDEX genres_title_key ON public.genres USING btree (title);

CREATE UNIQUE INDEX profiles_genres_pkey ON public.profiles_genres USING btree (profile, genre);

alter table "public"."genres" add constraint "genres_pkey" PRIMARY KEY using index "genres_pkey";

alter table "public"."profiles_genres" add constraint "profiles_genres_pkey" PRIMARY KEY using index "profiles_genres_pkey";

alter table "public"."genres" add constraint "genres_title_key" UNIQUE using index "genres_title_key";

alter table "public"."profiles_genres" add constraint "profiles_genres_genre_fkey" FOREIGN KEY (genre) REFERENCES genres(id) ON DELETE CASCADE not valid;

alter table "public"."profiles_genres" validate constraint "profiles_genres_genre_fkey";

alter table "public"."profiles_genres" add constraint "profiles_genres_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profiles_genres" validate constraint "profiles_genres_profile_fkey";

grant delete on table "public"."genres" to "anon";

grant insert on table "public"."genres" to "anon";

grant references on table "public"."genres" to "anon";

grant select on table "public"."genres" to "anon";

grant trigger on table "public"."genres" to "anon";

grant truncate on table "public"."genres" to "anon";

grant update on table "public"."genres" to "anon";

grant delete on table "public"."genres" to "authenticated";

grant insert on table "public"."genres" to "authenticated";

grant references on table "public"."genres" to "authenticated";

grant select on table "public"."genres" to "authenticated";

grant trigger on table "public"."genres" to "authenticated";

grant truncate on table "public"."genres" to "authenticated";

grant update on table "public"."genres" to "authenticated";

grant delete on table "public"."genres" to "service_role";

grant insert on table "public"."genres" to "service_role";

grant references on table "public"."genres" to "service_role";

grant select on table "public"."genres" to "service_role";

grant trigger on table "public"."genres" to "service_role";

grant truncate on table "public"."genres" to "service_role";

grant update on table "public"."genres" to "service_role";

grant delete on table "public"."profiles_genres" to "anon";

grant insert on table "public"."profiles_genres" to "anon";

grant references on table "public"."profiles_genres" to "anon";

grant select on table "public"."profiles_genres" to "anon";

grant trigger on table "public"."profiles_genres" to "anon";

grant truncate on table "public"."profiles_genres" to "anon";

grant update on table "public"."profiles_genres" to "anon";

grant delete on table "public"."profiles_genres" to "authenticated";

grant insert on table "public"."profiles_genres" to "authenticated";

grant references on table "public"."profiles_genres" to "authenticated";

grant select on table "public"."profiles_genres" to "authenticated";

grant trigger on table "public"."profiles_genres" to "authenticated";

grant truncate on table "public"."profiles_genres" to "authenticated";

grant update on table "public"."profiles_genres" to "authenticated";

grant delete on table "public"."profiles_genres" to "service_role";

grant insert on table "public"."profiles_genres" to "service_role";

grant references on table "public"."profiles_genres" to "service_role";

grant select on table "public"."profiles_genres" to "service_role";

grant trigger on table "public"."profiles_genres" to "service_role";

grant truncate on table "public"."profiles_genres" to "service_role";

grant update on table "public"."profiles_genres" to "service_role";


